// 操作数据的接口名称
export const GET_FAULT_LIST_TABLE_DATA = 'GET_FAULT_LIST_TABLE_DATA'; // 健康状态
export const GET_HEALTH_FIST_TABLE_DATA = 'GET_HEALTH_FIST_TABLE_DATA'; // 健康状态-主页表格
// export const GET_DEPOSITSPAGE4_PIEECHART1_DATA = 'GET_DEPOSITSPAGE4_PIEECHART1_DATA'; // 饼状图1
